// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	Address
	MultiAddress
	MultiAddresses
	Nothing
	Query
	OrderFragment
	OrderFragmentCommitment
	SyncBlock
	Final
	Shard
	DeltaShard
	DeltaFragment
	FinalizeShardRequest
	SyncRequest
	ElectShardRequest
	ComputeShardRequest
	Atom
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// An Address message is the network representation of an identity.Address.
type Address struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *Address) Reset()                    { *m = Address{} }
func (m *Address) String() string            { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()               {}
func (*Address) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// A MultiAddress is the network representation of an identity.MultiAddress.
type MultiAddress struct {
	Multi string `protobuf:"bytes,1,opt,name=multi" json:"multi,omitempty"`
}

func (m *MultiAddress) Reset()                    { *m = MultiAddress{} }
func (m *MultiAddress) String() string            { return proto.CompactTextString(m) }
func (*MultiAddress) ProtoMessage()               {}
func (*MultiAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MultiAddress) GetMulti() string {
	if m != nil {
		return m.Multi
	}
	return ""
}

// MultiAddresses are the network representation of identity.MultiAddresses.
type MultiAddresses struct {
	Multis []*MultiAddress `protobuf:"bytes,1,rep,name=multis" json:"multis,omitempty"`
}

func (m *MultiAddresses) Reset()                    { *m = MultiAddresses{} }
func (m *MultiAddresses) String() string            { return proto.CompactTextString(m) }
func (*MultiAddresses) ProtoMessage()               {}
func (*MultiAddresses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MultiAddresses) GetMultis() []*MultiAddress {
	if m != nil {
		return m.Multis
	}
	return nil
}

// Nothing is in this message. It is used to send nothing, or signal a
// successful response.
type Nothing struct {
}

func (m *Nothing) Reset()                    { *m = Nothing{} }
func (m *Nothing) String() string            { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()               {}
func (*Nothing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// A Query message contains the Address of a Node that needs to be found and
// the MultiAddress of the Node from which the Query originated.
type Query struct {
	// Network data.
	From *MultiAddress `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	// Public data.
	Query *Address `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Query) GetFrom() *MultiAddress {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Query) GetQuery() *Address {
	if m != nil {
		return m.Query
	}
	return nil
}

// An OrderFragment is a message contains the details of an order fragment.
type OrderFragment struct {
	// Network data.
	To   *Address      `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	From *MultiAddress `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	// Public data.
	Id          []byte `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	OrderId     []byte `protobuf:"bytes,4,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderType   int64  `protobuf:"varint,5,opt,name=orderType" json:"orderType,omitempty"`
	OrderParity int64  `protobuf:"varint,6,opt,name=orderParity" json:"orderParity,omitempty"`
	// Secure data.
	FstCodeShare   []byte `protobuf:"bytes,7,opt,name=fstCodeShare,proto3" json:"fstCodeShare,omitempty"`
	SndCodeShare   []byte `protobuf:"bytes,8,opt,name=sndCodeShare,proto3" json:"sndCodeShare,omitempty"`
	PriceShare     []byte `protobuf:"bytes,9,opt,name=priceShare,proto3" json:"priceShare,omitempty"`
	MaxVolumeShare []byte `protobuf:"bytes,10,opt,name=maxVolumeShare,proto3" json:"maxVolumeShare,omitempty"`
	MinVolumeShare []byte `protobuf:"bytes,11,opt,name=minVolumeShare,proto3" json:"minVolumeShare,omitempty"`
}

func (m *OrderFragment) Reset()                    { *m = OrderFragment{} }
func (m *OrderFragment) String() string            { return proto.CompactTextString(m) }
func (*OrderFragment) ProtoMessage()               {}
func (*OrderFragment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OrderFragment) GetTo() *Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *OrderFragment) GetFrom() *MultiAddress {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *OrderFragment) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *OrderFragment) GetOrderId() []byte {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *OrderFragment) GetOrderType() int64 {
	if m != nil {
		return m.OrderType
	}
	return 0
}

func (m *OrderFragment) GetOrderParity() int64 {
	if m != nil {
		return m.OrderParity
	}
	return 0
}

func (m *OrderFragment) GetFstCodeShare() []byte {
	if m != nil {
		return m.FstCodeShare
	}
	return nil
}

func (m *OrderFragment) GetSndCodeShare() []byte {
	if m != nil {
		return m.SndCodeShare
	}
	return nil
}

func (m *OrderFragment) GetPriceShare() []byte {
	if m != nil {
		return m.PriceShare
	}
	return nil
}

func (m *OrderFragment) GetMaxVolumeShare() []byte {
	if m != nil {
		return m.MaxVolumeShare
	}
	return nil
}

func (m *OrderFragment) GetMinVolumeShare() []byte {
	if m != nil {
		return m.MinVolumeShare
	}
	return nil
}

// An OrderFragmentCommitment is ...
type OrderFragmentCommitment struct {
	From          *MultiAddress `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Signature     []byte        `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	OrderFragment []byte        `protobuf:"bytes,3,opt,name=orderFragment,proto3" json:"orderFragment,omitempty"`
}

func (m *OrderFragmentCommitment) Reset()                    { *m = OrderFragmentCommitment{} }
func (m *OrderFragmentCommitment) String() string            { return proto.CompactTextString(m) }
func (*OrderFragmentCommitment) ProtoMessage()               {}
func (*OrderFragmentCommitment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *OrderFragmentCommitment) GetFrom() *MultiAddress {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *OrderFragmentCommitment) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *OrderFragmentCommitment) GetOrderFragment() []byte {
	if m != nil {
		return m.OrderFragment
	}
	return nil
}

// A SyncBlock is ...
type SyncBlock struct {
	Signature []byte                  `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Deltas    *SyncBlock_DeltaBlock   `protobuf:"bytes,2,opt,name=deltas" json:"deltas,omitempty"`
	Residues  *SyncBlock_ResidueBlock `protobuf:"bytes,3,opt,name=residues" json:"residues,omitempty"`
}

func (m *SyncBlock) Reset()                    { *m = SyncBlock{} }
func (m *SyncBlock) String() string            { return proto.CompactTextString(m) }
func (*SyncBlock) ProtoMessage()               {}
func (*SyncBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SyncBlock) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SyncBlock) GetDeltas() *SyncBlock_DeltaBlock {
	if m != nil {
		return m.Deltas
	}
	return nil
}

func (m *SyncBlock) GetResidues() *SyncBlock_ResidueBlock {
	if m != nil {
		return m.Residues
	}
	return nil
}

type SyncBlock_DeltaBlock struct {
	Pending    [][]byte `protobuf:"bytes,1,rep,name=pending,proto3" json:"pending,omitempty"`
	Electing   [][]byte `protobuf:"bytes,2,rep,name=electing,proto3" json:"electing,omitempty"`
	Computing  [][]byte `protobuf:"bytes,3,rep,name=computing,proto3" json:"computing,omitempty"`
	Finalizing [][]byte `protobuf:"bytes,4,rep,name=finalizing,proto3" json:"finalizing,omitempty"`
	Matched    [][]byte `protobuf:"bytes,5,rep,name=matched,proto3" json:"matched,omitempty"`
	Mismatched [][]byte `protobuf:"bytes,6,rep,name=mismatched,proto3" json:"mismatched,omitempty"`
}

func (m *SyncBlock_DeltaBlock) Reset()                    { *m = SyncBlock_DeltaBlock{} }
func (m *SyncBlock_DeltaBlock) String() string            { return proto.CompactTextString(m) }
func (*SyncBlock_DeltaBlock) ProtoMessage()               {}
func (*SyncBlock_DeltaBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

func (m *SyncBlock_DeltaBlock) GetPending() [][]byte {
	if m != nil {
		return m.Pending
	}
	return nil
}

func (m *SyncBlock_DeltaBlock) GetElecting() [][]byte {
	if m != nil {
		return m.Electing
	}
	return nil
}

func (m *SyncBlock_DeltaBlock) GetComputing() [][]byte {
	if m != nil {
		return m.Computing
	}
	return nil
}

func (m *SyncBlock_DeltaBlock) GetFinalizing() [][]byte {
	if m != nil {
		return m.Finalizing
	}
	return nil
}

func (m *SyncBlock_DeltaBlock) GetMatched() [][]byte {
	if m != nil {
		return m.Matched
	}
	return nil
}

func (m *SyncBlock_DeltaBlock) GetMismatched() [][]byte {
	if m != nil {
		return m.Mismatched
	}
	return nil
}

type SyncBlock_ResidueBlock struct {
	Pending    [][]byte `protobuf:"bytes,1,rep,name=pending,proto3" json:"pending,omitempty"`
	Electing   [][]byte `protobuf:"bytes,2,rep,name=electing,proto3" json:"electing,omitempty"`
	Computing  [][]byte `protobuf:"bytes,3,rep,name=computing,proto3" json:"computing,omitempty"`
	Finalizing [][]byte `protobuf:"bytes,4,rep,name=finalizing,proto3" json:"finalizing,omitempty"`
	Matched    [][]byte `protobuf:"bytes,5,rep,name=matched,proto3" json:"matched,omitempty"`
	Mismatched [][]byte `protobuf:"bytes,6,rep,name=mismatched,proto3" json:"mismatched,omitempty"`
}

func (m *SyncBlock_ResidueBlock) Reset()                    { *m = SyncBlock_ResidueBlock{} }
func (m *SyncBlock_ResidueBlock) String() string            { return proto.CompactTextString(m) }
func (*SyncBlock_ResidueBlock) ProtoMessage()               {}
func (*SyncBlock_ResidueBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 1} }

func (m *SyncBlock_ResidueBlock) GetPending() [][]byte {
	if m != nil {
		return m.Pending
	}
	return nil
}

func (m *SyncBlock_ResidueBlock) GetElecting() [][]byte {
	if m != nil {
		return m.Electing
	}
	return nil
}

func (m *SyncBlock_ResidueBlock) GetComputing() [][]byte {
	if m != nil {
		return m.Computing
	}
	return nil
}

func (m *SyncBlock_ResidueBlock) GetFinalizing() [][]byte {
	if m != nil {
		return m.Finalizing
	}
	return nil
}

func (m *SyncBlock_ResidueBlock) GetMatched() [][]byte {
	if m != nil {
		return m.Matched
	}
	return nil
}

func (m *SyncBlock_ResidueBlock) GetMismatched() [][]byte {
	if m != nil {
		return m.Mismatched
	}
	return nil
}

// Final messages are sent to signal that a successful order computation has
// happened.
type Final struct {
	// Public data.
	Id          []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyOrderId  []byte `protobuf:"bytes,2,opt,name=buyOrderId,proto3" json:"buyOrderId,omitempty"`
	SellOrderId []byte `protobuf:"bytes,3,opt,name=sellOrderId,proto3" json:"sellOrderId,omitempty"`
	// Secure data.
	FstCode   []byte `protobuf:"bytes,4,opt,name=fstCode,proto3" json:"fstCode,omitempty"`
	SndCode   []byte `protobuf:"bytes,5,opt,name=sndCode,proto3" json:"sndCode,omitempty"`
	Price     []byte `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	MaxVolume []byte `protobuf:"bytes,7,opt,name=maxVolume,proto3" json:"maxVolume,omitempty"`
	MinVolume []byte `protobuf:"bytes,8,opt,name=minVolume,proto3" json:"minVolume,omitempty"`
}

func (m *Final) Reset()                    { *m = Final{} }
func (m *Final) String() string            { return proto.CompactTextString(m) }
func (*Final) ProtoMessage()               {}
func (*Final) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Final) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Final) GetBuyOrderId() []byte {
	if m != nil {
		return m.BuyOrderId
	}
	return nil
}

func (m *Final) GetSellOrderId() []byte {
	if m != nil {
		return m.SellOrderId
	}
	return nil
}

func (m *Final) GetFstCode() []byte {
	if m != nil {
		return m.FstCode
	}
	return nil
}

func (m *Final) GetSndCode() []byte {
	if m != nil {
		return m.SndCode
	}
	return nil
}

func (m *Final) GetPrice() []byte {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Final) GetMaxVolume() []byte {
	if m != nil {
		return m.MaxVolume
	}
	return nil
}

func (m *Final) GetMinVolume() []byte {
	if m != nil {
		return m.MinVolume
	}
	return nil
}

// A shard is a block of computations
type Shard struct {
	Signature []byte           `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Deltas    []*DeltaFragment `protobuf:"bytes,2,rep,name=deltas" json:"deltas,omitempty"`
	Residues  [][]byte         `protobuf:"bytes,3,rep,name=residues,proto3" json:"residues,omitempty"`
}

func (m *Shard) Reset()                    { *m = Shard{} }
func (m *Shard) String() string            { return proto.CompactTextString(m) }
func (*Shard) ProtoMessage()               {}
func (*Shard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Shard) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Shard) GetDeltas() []*DeltaFragment {
	if m != nil {
		return m.Deltas
	}
	return nil
}

func (m *Shard) GetResidues() [][]byte {
	if m != nil {
		return m.Residues
	}
	return nil
}

// A DeltaShard is a block of results after computation
type DeltaShard struct {
	Signature []byte   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Finals    [][]byte `protobuf:"bytes,2,rep,name=finals,proto3" json:"finals,omitempty"`
}

func (m *DeltaShard) Reset()                    { *m = DeltaShard{} }
func (m *DeltaShard) String() string            { return proto.CompactTextString(m) }
func (*DeltaShard) ProtoMessage()               {}
func (*DeltaShard) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeltaShard) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *DeltaShard) GetFinals() [][]byte {
	if m != nil {
		return m.Finals
	}
	return nil
}

type DeltaFragment struct {
	Signature           []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Id                  []byte `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	BuyOrderID          []byte `protobuf:"bytes,3,opt,name=buyOrderID,proto3" json:"buyOrderID,omitempty"`
	SellOrderID         []byte `protobuf:"bytes,4,opt,name=sellOrderID,proto3" json:"sellOrderID,omitempty"`
	BuyOrderFragmentID  []byte `protobuf:"bytes,5,opt,name=buyOrderFragmentID,proto3" json:"buyOrderFragmentID,omitempty"`
	SellOrderFragmentID []byte `protobuf:"bytes,6,opt,name=sellOrderFragmentID,proto3" json:"sellOrderFragmentID,omitempty"`
	FstCodeShare        []byte `protobuf:"bytes,7,opt,name=fstCodeShare,proto3" json:"fstCodeShare,omitempty"`
	SndCodeShare        []byte `protobuf:"bytes,8,opt,name=sndCodeShare,proto3" json:"sndCodeShare,omitempty"`
	PriceShare          []byte `protobuf:"bytes,9,opt,name=priceShare,proto3" json:"priceShare,omitempty"`
	MaxVolumeShare      []byte `protobuf:"bytes,10,opt,name=maxVolumeShare,proto3" json:"maxVolumeShare,omitempty"`
	MinVolumeShare      []byte `protobuf:"bytes,11,opt,name=minVolumeShare,proto3" json:"minVolumeShare,omitempty"`
}

func (m *DeltaFragment) Reset()                    { *m = DeltaFragment{} }
func (m *DeltaFragment) String() string            { return proto.CompactTextString(m) }
func (*DeltaFragment) ProtoMessage()               {}
func (*DeltaFragment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeltaFragment) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *DeltaFragment) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DeltaFragment) GetBuyOrderID() []byte {
	if m != nil {
		return m.BuyOrderID
	}
	return nil
}

func (m *DeltaFragment) GetSellOrderID() []byte {
	if m != nil {
		return m.SellOrderID
	}
	return nil
}

func (m *DeltaFragment) GetBuyOrderFragmentID() []byte {
	if m != nil {
		return m.BuyOrderFragmentID
	}
	return nil
}

func (m *DeltaFragment) GetSellOrderFragmentID() []byte {
	if m != nil {
		return m.SellOrderFragmentID
	}
	return nil
}

func (m *DeltaFragment) GetFstCodeShare() []byte {
	if m != nil {
		return m.FstCodeShare
	}
	return nil
}

func (m *DeltaFragment) GetSndCodeShare() []byte {
	if m != nil {
		return m.SndCodeShare
	}
	return nil
}

func (m *DeltaFragment) GetPriceShare() []byte {
	if m != nil {
		return m.PriceShare
	}
	return nil
}

func (m *DeltaFragment) GetMaxVolumeShare() []byte {
	if m != nil {
		return m.MaxVolumeShare
	}
	return nil
}

func (m *DeltaFragment) GetMinVolumeShare() []byte {
	if m != nil {
		return m.MinVolumeShare
	}
	return nil
}

// A FinalizeShardRequest is ...
type FinalizeShardRequest struct {
	From  *MultiAddress `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Shard *DeltaShard   `protobuf:"bytes,2,opt,name=shard" json:"shard,omitempty"`
}

func (m *FinalizeShardRequest) Reset()                    { *m = FinalizeShardRequest{} }
func (m *FinalizeShardRequest) String() string            { return proto.CompactTextString(m) }
func (*FinalizeShardRequest) ProtoMessage()               {}
func (*FinalizeShardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *FinalizeShardRequest) GetFrom() *MultiAddress {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *FinalizeShardRequest) GetShard() *DeltaShard {
	if m != nil {
		return m.Shard
	}
	return nil
}

// A SyncRequest is ...
type SyncRequest struct {
	From *MultiAddress `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
}

func (m *SyncRequest) Reset()                    { *m = SyncRequest{} }
func (m *SyncRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncRequest) ProtoMessage()               {}
func (*SyncRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SyncRequest) GetFrom() *MultiAddress {
	if m != nil {
		return m.From
	}
	return nil
}

// A ElectShardRequest is ...
type ElectShardRequest struct {
	From  *MultiAddress `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Shard *Shard        `protobuf:"bytes,2,opt,name=shard" json:"shard,omitempty"`
}

func (m *ElectShardRequest) Reset()                    { *m = ElectShardRequest{} }
func (m *ElectShardRequest) String() string            { return proto.CompactTextString(m) }
func (*ElectShardRequest) ProtoMessage()               {}
func (*ElectShardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ElectShardRequest) GetFrom() *MultiAddress {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ElectShardRequest) GetShard() *Shard {
	if m != nil {
		return m.Shard
	}
	return nil
}

// A ComputeShardRequest is ...
type ComputeShardRequest struct {
	From  *MultiAddress `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Shard *Shard        `protobuf:"bytes,2,opt,name=shard" json:"shard,omitempty"`
}

func (m *ComputeShardRequest) Reset()                    { *m = ComputeShardRequest{} }
func (m *ComputeShardRequest) String() string            { return proto.CompactTextString(m) }
func (*ComputeShardRequest) ProtoMessage()               {}
func (*ComputeShardRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ComputeShardRequest) GetFrom() *MultiAddress {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ComputeShardRequest) GetShard() *Shard {
	if m != nil {
		return m.Shard
	}
	return nil
}

// An Atom message is the network representation of a atom.Atom and the
// metadata needed to distribute it through the network.
type Atom struct {
	// Network data.
	To   *Address      `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	From *MultiAddress `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	// Secure data.
	Ledger    int64  `protobuf:"varint,3,opt,name=ledger" json:"ledger,omitempty"`
	Data      []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Atom) Reset()                    { *m = Atom{} }
func (m *Atom) String() string            { return proto.CompactTextString(m) }
func (*Atom) ProtoMessage()               {}
func (*Atom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Atom) GetTo() *Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Atom) GetFrom() *MultiAddress {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Atom) GetLedger() int64 {
	if m != nil {
		return m.Ledger
	}
	return 0
}

func (m *Atom) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Atom) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "rpc.Address")
	proto.RegisterType((*MultiAddress)(nil), "rpc.MultiAddress")
	proto.RegisterType((*MultiAddresses)(nil), "rpc.MultiAddresses")
	proto.RegisterType((*Nothing)(nil), "rpc.Nothing")
	proto.RegisterType((*Query)(nil), "rpc.Query")
	proto.RegisterType((*OrderFragment)(nil), "rpc.OrderFragment")
	proto.RegisterType((*OrderFragmentCommitment)(nil), "rpc.OrderFragmentCommitment")
	proto.RegisterType((*SyncBlock)(nil), "rpc.SyncBlock")
	proto.RegisterType((*SyncBlock_DeltaBlock)(nil), "rpc.SyncBlock.DeltaBlock")
	proto.RegisterType((*SyncBlock_ResidueBlock)(nil), "rpc.SyncBlock.ResidueBlock")
	proto.RegisterType((*Final)(nil), "rpc.Final")
	proto.RegisterType((*Shard)(nil), "rpc.Shard")
	proto.RegisterType((*DeltaShard)(nil), "rpc.DeltaShard")
	proto.RegisterType((*DeltaFragment)(nil), "rpc.DeltaFragment")
	proto.RegisterType((*FinalizeShardRequest)(nil), "rpc.FinalizeShardRequest")
	proto.RegisterType((*SyncRequest)(nil), "rpc.SyncRequest")
	proto.RegisterType((*ElectShardRequest)(nil), "rpc.ElectShardRequest")
	proto.RegisterType((*ComputeShardRequest)(nil), "rpc.ComputeShardRequest")
	proto.RegisterType((*Atom)(nil), "rpc.Atom")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SwarmNode service

type SwarmNodeClient interface {
	// Ping the connection and swap MultiAddresses.
	Ping(ctx context.Context, in *MultiAddress, opts ...grpc.CallOption) (*Nothing, error)
	// Find the MultiAddresses of peers closer to some target Node.
	QueryCloserPeers(ctx context.Context, in *Query, opts ...grpc.CallOption) (*MultiAddresses, error)
	// Find the MultiAddresses of peers closer to some target Node using a
	// frontier search.
	QueryCloserPeersOnFrontier(ctx context.Context, in *Query, opts ...grpc.CallOption) (SwarmNode_QueryCloserPeersOnFrontierClient, error)
}

type swarmNodeClient struct {
	cc *grpc.ClientConn
}

func NewSwarmNodeClient(cc *grpc.ClientConn) SwarmNodeClient {
	return &swarmNodeClient{cc}
}

func (c *swarmNodeClient) Ping(ctx context.Context, in *MultiAddress, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := grpc.Invoke(ctx, "/rpc.SwarmNode/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swarmNodeClient) QueryCloserPeers(ctx context.Context, in *Query, opts ...grpc.CallOption) (*MultiAddresses, error) {
	out := new(MultiAddresses)
	err := grpc.Invoke(ctx, "/rpc.SwarmNode/QueryCloserPeers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swarmNodeClient) QueryCloserPeersOnFrontier(ctx context.Context, in *Query, opts ...grpc.CallOption) (SwarmNode_QueryCloserPeersOnFrontierClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SwarmNode_serviceDesc.Streams[0], c.cc, "/rpc.SwarmNode/QueryCloserPeersOnFrontier", opts...)
	if err != nil {
		return nil, err
	}
	x := &swarmNodeQueryCloserPeersOnFrontierClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SwarmNode_QueryCloserPeersOnFrontierClient interface {
	Recv() (*MultiAddress, error)
	grpc.ClientStream
}

type swarmNodeQueryCloserPeersOnFrontierClient struct {
	grpc.ClientStream
}

func (x *swarmNodeQueryCloserPeersOnFrontierClient) Recv() (*MultiAddress, error) {
	m := new(MultiAddress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SwarmNode service

type SwarmNodeServer interface {
	// Ping the connection and swap MultiAddresses.
	Ping(context.Context, *MultiAddress) (*Nothing, error)
	// Find the MultiAddresses of peers closer to some target Node.
	QueryCloserPeers(context.Context, *Query) (*MultiAddresses, error)
	// Find the MultiAddresses of peers closer to some target Node using a
	// frontier search.
	QueryCloserPeersOnFrontier(*Query, SwarmNode_QueryCloserPeersOnFrontierServer) error
}

func RegisterSwarmNodeServer(s *grpc.Server, srv SwarmNodeServer) {
	s.RegisterService(&_SwarmNode_serviceDesc, srv)
}

func _SwarmNode_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmNodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SwarmNode/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmNodeServer).Ping(ctx, req.(*MultiAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwarmNode_QueryCloserPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmNodeServer).QueryCloserPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.SwarmNode/QueryCloserPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmNodeServer).QueryCloserPeers(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwarmNode_QueryCloserPeersOnFrontier_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SwarmNodeServer).QueryCloserPeersOnFrontier(m, &swarmNodeQueryCloserPeersOnFrontierServer{stream})
}

type SwarmNode_QueryCloserPeersOnFrontierServer interface {
	Send(*MultiAddress) error
	grpc.ServerStream
}

type swarmNodeQueryCloserPeersOnFrontierServer struct {
	grpc.ServerStream
}

func (x *swarmNodeQueryCloserPeersOnFrontierServer) Send(m *MultiAddress) error {
	return x.ServerStream.SendMsg(m)
}

var _SwarmNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.SwarmNode",
	HandlerType: (*SwarmNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SwarmNode_Ping_Handler,
		},
		{
			MethodName: "QueryCloserPeers",
			Handler:    _SwarmNode_QueryCloserPeers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryCloserPeersOnFrontier",
			Handler:       _SwarmNode_QueryCloserPeersOnFrontier_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc.proto",
}

// Client API for DarkNode service

type DarkNodeClient interface {
	// Send a sync request for getting new shard
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (DarkNode_SyncClient, error)
	// Send a commitment to the order fragment.
	SendOrderFragmentCommitment(ctx context.Context, in *OrderFragmentCommitment, opts ...grpc.CallOption) (*OrderFragmentCommitment, error)
	// Send an OrderFragment to some target Node.
	SendOrderFragment(ctx context.Context, in *OrderFragment, opts ...grpc.CallOption) (*Nothing, error)
	// Propose a shard election request to some target node.
	ElectShard(ctx context.Context, in *ElectShardRequest, opts ...grpc.CallOption) (*Shard, error)
	// Ask some target node to start computation on the shard.
	ComputeShard(ctx context.Context, in *ComputeShardRequest, opts ...grpc.CallOption) (*Nothing, error)
	//
	FinalizeShard(ctx context.Context, in *FinalizeShardRequest, opts ...grpc.CallOption) (*Nothing, error)
}

type darkNodeClient struct {
	cc *grpc.ClientConn
}

func NewDarkNodeClient(cc *grpc.ClientConn) DarkNodeClient {
	return &darkNodeClient{cc}
}

func (c *darkNodeClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (DarkNode_SyncClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DarkNode_serviceDesc.Streams[0], c.cc, "/rpc.DarkNode/Sync", opts...)
	if err != nil {
		return nil, err
	}
	x := &darkNodeSyncClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DarkNode_SyncClient interface {
	Recv() (*SyncBlock, error)
	grpc.ClientStream
}

type darkNodeSyncClient struct {
	grpc.ClientStream
}

func (x *darkNodeSyncClient) Recv() (*SyncBlock, error) {
	m := new(SyncBlock)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *darkNodeClient) SendOrderFragmentCommitment(ctx context.Context, in *OrderFragmentCommitment, opts ...grpc.CallOption) (*OrderFragmentCommitment, error) {
	out := new(OrderFragmentCommitment)
	err := grpc.Invoke(ctx, "/rpc.DarkNode/SendOrderFragmentCommitment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkNodeClient) SendOrderFragment(ctx context.Context, in *OrderFragment, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := grpc.Invoke(ctx, "/rpc.DarkNode/SendOrderFragment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkNodeClient) ElectShard(ctx context.Context, in *ElectShardRequest, opts ...grpc.CallOption) (*Shard, error) {
	out := new(Shard)
	err := grpc.Invoke(ctx, "/rpc.DarkNode/ElectShard", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkNodeClient) ComputeShard(ctx context.Context, in *ComputeShardRequest, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := grpc.Invoke(ctx, "/rpc.DarkNode/ComputeShard", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *darkNodeClient) FinalizeShard(ctx context.Context, in *FinalizeShardRequest, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := grpc.Invoke(ctx, "/rpc.DarkNode/FinalizeShard", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DarkNode service

type DarkNodeServer interface {
	// Send a sync request for getting new shard
	Sync(*SyncRequest, DarkNode_SyncServer) error
	// Send a commitment to the order fragment.
	SendOrderFragmentCommitment(context.Context, *OrderFragmentCommitment) (*OrderFragmentCommitment, error)
	// Send an OrderFragment to some target Node.
	SendOrderFragment(context.Context, *OrderFragment) (*Nothing, error)
	// Propose a shard election request to some target node.
	ElectShard(context.Context, *ElectShardRequest) (*Shard, error)
	// Ask some target node to start computation on the shard.
	ComputeShard(context.Context, *ComputeShardRequest) (*Nothing, error)
	//
	FinalizeShard(context.Context, *FinalizeShardRequest) (*Nothing, error)
}

func RegisterDarkNodeServer(s *grpc.Server, srv DarkNodeServer) {
	s.RegisterService(&_DarkNode_serviceDesc, srv)
}

func _DarkNode_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DarkNodeServer).Sync(m, &darkNodeSyncServer{stream})
}

type DarkNode_SyncServer interface {
	Send(*SyncBlock) error
	grpc.ServerStream
}

type darkNodeSyncServer struct {
	grpc.ServerStream
}

func (x *darkNodeSyncServer) Send(m *SyncBlock) error {
	return x.ServerStream.SendMsg(m)
}

func _DarkNode_SendOrderFragmentCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderFragmentCommitment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkNodeServer).SendOrderFragmentCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DarkNode/SendOrderFragmentCommitment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkNodeServer).SendOrderFragmentCommitment(ctx, req.(*OrderFragmentCommitment))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkNode_SendOrderFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderFragment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkNodeServer).SendOrderFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DarkNode/SendOrderFragment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkNodeServer).SendOrderFragment(ctx, req.(*OrderFragment))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkNode_ElectShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElectShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkNodeServer).ElectShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DarkNode/ElectShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkNodeServer).ElectShard(ctx, req.(*ElectShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkNode_ComputeShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkNodeServer).ComputeShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DarkNode/ComputeShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkNodeServer).ComputeShard(ctx, req.(*ComputeShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DarkNode_FinalizeShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DarkNodeServer).FinalizeShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.DarkNode/FinalizeShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DarkNodeServer).FinalizeShard(ctx, req.(*FinalizeShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DarkNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.DarkNode",
	HandlerType: (*DarkNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOrderFragmentCommitment",
			Handler:    _DarkNode_SendOrderFragmentCommitment_Handler,
		},
		{
			MethodName: "SendOrderFragment",
			Handler:    _DarkNode_SendOrderFragment_Handler,
		},
		{
			MethodName: "ElectShard",
			Handler:    _DarkNode_ElectShard_Handler,
		},
		{
			MethodName: "ComputeShard",
			Handler:    _DarkNode_ComputeShard_Handler,
		},
		{
			MethodName: "FinalizeShard",
			Handler:    _DarkNode_FinalizeShard_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _DarkNode_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc.proto",
}

// Client API for TerminalNode service

type TerminalNodeClient interface {
	// Send an Atom to some target Node.
	SendAtom(ctx context.Context, in *Atom, opts ...grpc.CallOption) (*Atom, error)
}

type terminalNodeClient struct {
	cc *grpc.ClientConn
}

func NewTerminalNodeClient(cc *grpc.ClientConn) TerminalNodeClient {
	return &terminalNodeClient{cc}
}

func (c *terminalNodeClient) SendAtom(ctx context.Context, in *Atom, opts ...grpc.CallOption) (*Atom, error) {
	out := new(Atom)
	err := grpc.Invoke(ctx, "/rpc.TerminalNode/SendAtom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TerminalNode service

type TerminalNodeServer interface {
	// Send an Atom to some target Node.
	SendAtom(context.Context, *Atom) (*Atom, error)
}

func RegisterTerminalNodeServer(s *grpc.Server, srv TerminalNodeServer) {
	s.RegisterService(&_TerminalNode_serviceDesc, srv)
}

func _TerminalNode_SendAtom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Atom)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalNodeServer).SendAtom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.TerminalNode/SendAtom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalNodeServer).SendAtom(ctx, req.(*Atom))
	}
	return interceptor(ctx, in, info, handler)
}

var _TerminalNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.TerminalNode",
	HandlerType: (*TerminalNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAtom",
			Handler:    _TerminalNode_SendAtom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1011 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x4f, 0x8f, 0xdb, 0x44,
	0x14, 0x97, 0x9d, 0x38, 0x1b, 0xbf, 0x78, 0x97, 0xee, 0x6c, 0xb5, 0x18, 0x77, 0x55, 0x45, 0xa6,
	0x85, 0xa5, 0x87, 0x55, 0x48, 0xf9, 0x27, 0x21, 0x0e, 0xed, 0x86, 0x95, 0x7a, 0xa0, 0xbb, 0x38,
	0x15, 0x12, 0x12, 0x42, 0x72, 0x33, 0xb3, 0x59, 0xab, 0xfe, 0x93, 0x8e, 0x27, 0x82, 0x70, 0xe6,
	0x0b, 0x70, 0xe0, 0xc0, 0x37, 0xe0, 0x33, 0x20, 0xbe, 0x0b, 0x5f, 0x80, 0x33, 0x67, 0x34, 0x6f,
	0xc6, 0xf6, 0x38, 0x49, 0xdb, 0x05, 0xc1, 0xa1, 0x37, 0xbf, 0xf7, 0xfb, 0xbd, 0xf7, 0xc6, 0x7e,
	0xbf, 0xf7, 0x32, 0x01, 0x97, 0x2f, 0x66, 0x27, 0x0b, 0x5e, 0x88, 0x82, 0x74, 0xf8, 0x62, 0x16,
	0xbe, 0x0d, 0x3b, 0x0f, 0x28, 0xe5, 0xac, 0x2c, 0x89, 0x0f, 0x3b, 0xb1, 0x7a, 0xf4, 0xad, 0xa1,
	0x75, 0xec, 0x46, 0x95, 0x19, 0xde, 0x01, 0xef, 0x8b, 0x65, 0x2a, 0x92, 0x8a, 0x79, 0x13, 0x9c,
	0x4c, 0xda, 0x9a, 0xa7, 0x8c, 0xf0, 0x53, 0xd8, 0x33, 0x59, 0xac, 0x24, 0xef, 0x41, 0x0f, 0x21,
	0x99, 0xb0, 0x73, 0x3c, 0x18, 0xef, 0x9f, 0xc8, 0xea, 0x26, 0x29, 0xd2, 0x84, 0xd0, 0x85, 0x9d,
	0xc7, 0x85, 0xb8, 0x4a, 0xf2, 0x79, 0x18, 0x81, 0xf3, 0xe5, 0x92, 0xf1, 0x15, 0xb9, 0x0b, 0xdd,
	0x4b, 0x5e, 0x64, 0x58, 0x65, 0x6b, 0x30, 0xc2, 0x24, 0x04, 0xe7, 0xb9, 0xe4, 0xfb, 0x36, 0xf2,
	0x3c, 0xe4, 0x55, 0x14, 0x05, 0x85, 0x7f, 0xd9, 0xb0, 0x7b, 0xce, 0x29, 0xe3, 0x67, 0x3c, 0x9e,
	0x67, 0x2c, 0x17, 0xe4, 0x08, 0x6c, 0x51, 0xe8, 0xd4, 0xed, 0x10, 0x5b, 0x14, 0x75, 0x69, 0xfb,
	0xe5, 0xa5, 0xf7, 0xc0, 0x4e, 0xa8, 0xdf, 0x19, 0x5a, 0xc7, 0x5e, 0x64, 0x27, 0x54, 0x7e, 0xc2,
	0x42, 0x56, 0x79, 0x44, 0xfd, 0x2e, 0x3a, 0x2b, 0x93, 0x1c, 0x81, 0x8b, 0x8f, 0x4f, 0x56, 0x0b,
	0xe6, 0x3b, 0x43, 0xeb, 0xb8, 0x13, 0x35, 0x0e, 0x32, 0x84, 0x01, 0x1a, 0x17, 0x31, 0x4f, 0xc4,
	0xca, 0xef, 0x21, 0x6e, 0xba, 0x48, 0x08, 0xde, 0x65, 0x29, 0x4e, 0x0b, 0xca, 0xa6, 0x57, 0x31,
	0x67, 0xfe, 0x0e, 0xa6, 0x6f, 0xf9, 0x24, 0xa7, 0xcc, 0x69, 0xc3, 0xe9, 0x2b, 0x8e, 0xe9, 0x23,
	0xb7, 0x01, 0x16, 0x3c, 0x99, 0x69, 0x86, 0x8b, 0x0c, 0xc3, 0x43, 0xde, 0x81, 0xbd, 0x2c, 0xfe,
	0xfe, 0xab, 0x22, 0x5d, 0x66, 0x9a, 0x03, 0xc8, 0x59, 0xf3, 0x22, 0x2f, 0xc9, 0x4d, 0xde, 0x40,
	0xf3, 0x5a, 0xde, 0xf0, 0x47, 0x0b, 0xde, 0x6c, 0x7d, 0xf8, 0xd3, 0x22, 0xcb, 0x12, 0x81, 0x2d,
	0xb8, 0x66, 0x7f, 0x8f, 0xc0, 0x2d, 0x93, 0x79, 0x1e, 0x8b, 0x25, 0x67, 0xd8, 0x10, 0x2f, 0x6a,
	0x1c, 0xe4, 0x0e, 0xec, 0x16, 0x66, 0x7e, 0xdd, 0x8d, 0xb6, 0x33, 0xfc, 0xa9, 0x0b, 0xee, 0x74,
	0x95, 0xcf, 0x1e, 0xa6, 0xc5, 0xec, 0x59, 0x3b, 0xa3, 0xb5, 0x9e, 0xf1, 0x7d, 0xe8, 0x51, 0x96,
	0x8a, 0xb8, 0xd4, 0xdd, 0x7f, 0x0b, 0x0f, 0x56, 0x47, 0x9f, 0x4c, 0x24, 0x88, 0x8f, 0x91, 0x26,
	0x92, 0x8f, 0xa1, 0xcf, 0x59, 0x99, 0xd0, 0x25, 0x2b, 0xb1, 0xfe, 0x60, 0x7c, 0x6b, 0x2d, 0x28,
	0x52, 0xb0, 0x0a, 0xab, 0xc9, 0xc1, 0x6f, 0x16, 0x40, 0x93, 0x4f, 0xea, 0x67, 0xc1, 0x72, 0x9a,
	0xe4, 0x73, 0x9c, 0x18, 0x2f, 0xaa, 0x4c, 0x12, 0x40, 0x9f, 0xa5, 0x6c, 0x26, 0x24, 0x64, 0x23,
	0x54, 0xdb, 0xf2, 0x75, 0x66, 0x45, 0xb6, 0x58, 0x22, 0xd8, 0x41, 0xb0, 0x71, 0xc8, 0x8e, 0x5f,
	0x26, 0x79, 0x9c, 0x26, 0x3f, 0x48, 0xb8, 0x8b, 0xb0, 0xe1, 0x91, 0x35, 0xb3, 0x58, 0xcc, 0xae,
	0x18, 0xf5, 0x1d, 0x55, 0x53, 0x9b, 0x32, 0x32, 0x4b, 0xca, 0x0a, 0xec, 0xa9, 0xc8, 0xc6, 0x13,
	0xfc, 0x6e, 0x81, 0x67, 0xbe, 0xd7, 0xeb, 0x75, 0xfc, 0xf0, 0x0f, 0x0b, 0x9c, 0x33, 0x99, 0x48,
	0x8f, 0xb1, 0x55, 0x8f, 0xf1, 0x6d, 0x80, 0xa7, 0xcb, 0xd5, 0xb9, 0x9e, 0x64, 0x25, 0x39, 0xc3,
	0x23, 0xc7, 0xb5, 0x64, 0x69, 0x5a, 0x11, 0x94, 0xe2, 0x4c, 0x97, 0x3c, 0x95, 0x1e, 0xcd, 0x6a,
	0x11, 0x68, 0x53, 0x22, 0x7a, 0x20, 0x71, 0x0d, 0x78, 0x51, 0x65, 0xca, 0xad, 0x8a, 0x83, 0x88,
	0xe3, 0xef, 0x45, 0xca, 0x90, 0x5f, 0xa7, 0x1e, 0x3d, 0x3d, 0xf5, 0x8d, 0x03, 0xd1, 0x6a, 0xe0,
	0xf4, 0xbc, 0x37, 0x8e, 0x30, 0x03, 0x47, 0x4e, 0x21, 0x7d, 0x85, 0xe0, 0xef, 0x19, 0x82, 0x97,
	0x6b, 0x9a, 0xa0, 0x76, 0x51, 0x96, 0xd5, 0x00, 0xd5, 0x4a, 0x0f, 0x5a, 0x4a, 0xc7, 0x46, 0x56,
	0x76, 0xf8, 0x50, 0x6b, 0xf9, 0x3a, 0x35, 0x0f, 0xa1, 0x87, 0x4d, 0x2c, 0xb5, 0x1c, 0xb4, 0x15,
	0xfe, 0xd2, 0x81, 0xdd, 0x56, 0xe5, 0x57, 0xe4, 0x51, 0xad, 0xb3, 0xb7, 0xb6, 0x6e, 0xa2, 0x3b,
	0x63, 0x78, 0xda, 0xad, 0x9b, 0xe8, 0xe6, 0x98, 0x2e, 0x72, 0x02, 0xa4, 0xe2, 0x57, 0x67, 0x78,
	0x34, 0xd1, 0xbd, 0xda, 0x82, 0x90, 0x11, 0x1c, 0xd4, 0xe1, 0x46, 0x80, 0x6a, 0xe2, 0x36, 0xe8,
	0xb5, 0xdd, 0xe5, 0x14, 0x6e, 0x9e, 0xa9, 0xc1, 0x43, 0x07, 0x8d, 0xd8, 0xf3, 0x25, 0x2b, 0xaf,
	0xbd, 0xc7, 0xef, 0x82, 0x53, 0xca, 0x30, 0xbd, 0x56, 0xdf, 0x68, 0x54, 0xa6, 0xb2, 0x29, 0x34,
	0xfc, 0x00, 0x06, 0x72, 0x6d, 0xfe, 0xb3, 0xe4, 0xe1, 0x37, 0xb0, 0xff, 0xb9, 0x5c, 0x28, 0xff,
	0xe6, 0x60, 0xc3, 0xf6, 0xc1, 0x40, 0xad, 0x6e, 0xf3, 0x4c, 0xdf, 0xc2, 0xc1, 0x29, 0x6e, 0x24,
	0xf6, 0xff, 0xe4, 0xff, 0xd9, 0x82, 0xee, 0x03, 0x81, 0xbf, 0x75, 0xff, 0xc1, 0xad, 0xe4, 0x10,
	0x7a, 0x29, 0xa3, 0x73, 0xc6, 0x51, 0xff, 0x9d, 0x48, 0x5b, 0x84, 0x40, 0x97, 0xc6, 0x22, 0xd6,
	0xa2, 0xc7, 0xe7, 0xf6, 0x74, 0x39, 0x6b, 0xd3, 0x35, 0xfe, 0xd5, 0x02, 0x77, 0xfa, 0x5d, 0xcc,
	0xb3, 0xc7, 0x72, 0x41, 0xbd, 0x0b, 0xdd, 0x0b, 0xb9, 0x72, 0x37, 0x0b, 0x07, 0xea, 0xac, 0xfa,
	0x06, 0x47, 0xee, 0xc3, 0x0d, 0xbc, 0xc1, 0x9d, 0xa6, 0x45, 0xc9, 0xf8, 0x05, 0x63, 0xbc, 0x24,
	0xea, 0xad, 0xd1, 0x1d, 0x1c, 0x6c, 0x24, 0x60, 0x25, 0xf9, 0x0c, 0x82, 0xf5, 0xa0, 0xf3, 0xfc,
	0x8c, 0x17, 0xb9, 0x48, 0x18, 0x6f, 0x85, 0x6f, 0xd6, 0x1f, 0x59, 0xe3, 0x3f, 0x6d, 0xe8, 0x4f,
	0x62, 0xfe, 0x0c, 0x4f, 0x7a, 0x0f, 0xba, 0x52, 0x43, 0xe4, 0x46, 0xfd, 0x2b, 0xac, 0x5b, 0x16,
	0xec, 0xb5, 0x7f, 0x97, 0x47, 0x16, 0xf9, 0x1a, 0x6e, 0x4d, 0x59, 0x4e, 0x5f, 0x74, 0x49, 0x39,
	0xc2, 0x80, 0x17, 0xa0, 0xc1, 0x4b, 0x51, 0xf2, 0x21, 0xec, 0x6f, 0xa4, 0x26, 0x64, 0x33, 0x64,
	0xed, 0xf3, 0x8d, 0x00, 0x1a, 0x2d, 0x93, 0x43, 0xc4, 0x36, 0xc4, 0x1d, 0x18, 0x32, 0x22, 0x1f,
	0x81, 0x67, 0xea, 0x93, 0xf8, 0x88, 0x6d, 0x91, 0xec, 0x5a, 0xa5, 0x4f, 0x60, 0xb7, 0x35, 0xd1,
	0x44, 0xdd, 0x75, 0xb6, 0x4d, 0x79, 0x3b, 0x72, 0x3c, 0x02, 0xef, 0x09, 0xe3, 0x99, 0x24, 0xe2,
	0x17, 0x1f, 0x42, 0x5f, 0xbe, 0x2a, 0x8a, 0xd8, 0x55, 0xc2, 0x15, 0x45, 0x16, 0x34, 0x8f, 0x4f,
	0x7b, 0xf8, 0xaf, 0xe3, 0xfe, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xdc, 0x18, 0xdb, 0x82,
	0x0c, 0x00, 0x00,
}
