// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	OrderFragment
	MultiAddress
	MultiAddresses
	Nothing
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// An OrderFragment is a message contains the details of an order fragment.
type OrderFragment struct {
	To              string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	OrderID         []byte `protobuf:"bytes,2,opt,name=orderID,proto3" json:"orderID,omitempty"`
	OrderFragmentID []byte `protobuf:"bytes,3,opt,name=orderFragmentID,proto3" json:"orderFragmentID,omitempty"`
	OrderFragment   []byte `protobuf:"bytes,4,opt,name=orderFragment,proto3" json:"orderFragment,omitempty"`
}

func (m *OrderFragment) Reset()                    { *m = OrderFragment{} }
func (m *OrderFragment) String() string            { return proto.CompactTextString(m) }
func (*OrderFragment) ProtoMessage()               {}
func (*OrderFragment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OrderFragment) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *OrderFragment) GetOrderID() []byte {
	if m != nil {
		return m.OrderID
	}
	return nil
}

func (m *OrderFragment) GetOrderFragmentID() []byte {
	if m != nil {
		return m.OrderFragmentID
	}
	return nil
}

func (m *OrderFragment) GetOrderFragment() []byte {
	if m != nil {
		return m.OrderFragment
	}
	return nil
}

// A MultiAddress is the public multiaddress of a Node in the overlay network.
// It provides the Republic address of the Node, as well as the network
// address.
type MultiAddress struct {
	Multi string `protobuf:"bytes,1,opt,name=multi" json:"multi,omitempty"`
}

func (m *MultiAddress) Reset()                    { *m = MultiAddress{} }
func (m *MultiAddress) String() string            { return proto.CompactTextString(m) }
func (*MultiAddress) ProtoMessage()               {}
func (*MultiAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MultiAddress) GetMulti() string {
	if m != nil {
		return m.Multi
	}
	return ""
}

// MultiAddresses are public multiaddress of multiple Nodes in the overlay
// network.
type MultiAddresses struct {
	Multis []*MultiAddress `protobuf:"bytes,1,rep,name=multis" json:"multis,omitempty"`
}

func (m *MultiAddresses) Reset()                    { *m = MultiAddresses{} }
func (m *MultiAddresses) String() string            { return proto.CompactTextString(m) }
func (*MultiAddresses) ProtoMessage()               {}
func (*MultiAddresses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MultiAddresses) GetMultis() []*MultiAddress {
	if m != nil {
		return m.Multis
	}
	return nil
}

// Nothing is in this message. It is used to send nothing, or signal a
// successful response.
type Nothing struct {
}

func (m *Nothing) Reset()                    { *m = Nothing{} }
func (m *Nothing) String() string            { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()               {}
func (*Nothing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*OrderFragment)(nil), "rpc.OrderFragment")
	proto.RegisterType((*MultiAddress)(nil), "rpc.MultiAddress")
	proto.RegisterType((*MultiAddresses)(nil), "rpc.MultiAddresses")
	proto.RegisterType((*Nothing)(nil), "rpc.Nothing")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Node service

type NodeClient interface {
	// Ping the connection and swap MultiAddresses.
	Ping(ctx context.Context, in *MultiAddress, opts ...grpc.CallOption) (*MultiAddress, error)
	// Get all peers connected to the Node.
	Peers(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*MultiAddresses, error)
	// Send an order fragment to some target Node.
	SendOrderFragment(ctx context.Context, in *OrderFragment, opts ...grpc.CallOption) (*Nothing, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Ping(ctx context.Context, in *MultiAddress, opts ...grpc.CallOption) (*MultiAddress, error) {
	out := new(MultiAddress)
	err := grpc.Invoke(ctx, "/rpc.Node/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Peers(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*MultiAddresses, error) {
	out := new(MultiAddresses)
	err := grpc.Invoke(ctx, "/rpc.Node/Peers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) SendOrderFragment(ctx context.Context, in *OrderFragment, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := grpc.Invoke(ctx, "/rpc.Node/SendOrderFragment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeServer interface {
	// Ping the connection and swap MultiAddresses.
	Ping(context.Context, *MultiAddress) (*MultiAddress, error)
	// Get all peers connected to the Node.
	Peers(context.Context, *Nothing) (*MultiAddresses, error)
	// Send an order fragment to some target Node.
	SendOrderFragment(context.Context, *OrderFragment) (*Nothing, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Node/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Ping(ctx, req.(*MultiAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Peers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Peers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Node/Peers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Peers(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_SendOrderFragment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderFragment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).SendOrderFragment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Node/SendOrderFragment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).SendOrderFragment(ctx, req.(*OrderFragment))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Node_Ping_Handler,
		},
		{
			MethodName: "Peers",
			Handler:    _Node_Peers_Handler,
		},
		{
			MethodName: "SendOrderFragment",
			Handler:    _Node_SendOrderFragment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xd9, 0x24, 0x6d, 0xc9, 0x98, 0x56, 0x3a, 0x7a, 0x58, 0x72, 0x0a, 0xa1, 0x87, 0x28,
	0xd2, 0x43, 0xc5, 0x93, 0x27, 0xa1, 0x08, 0x3d, 0x58, 0x4b, 0x7c, 0x02, 0xed, 0x0e, 0x31, 0x60,
	0xb3, 0x61, 0x76, 0x7d, 0x08, 0x9f, 0xc0, 0xd7, 0x95, 0xac, 0x11, 0xb2, 0xe6, 0xf8, 0xfd, 0xe6,
	0x37, 0x1f, 0xfb, 0x07, 0x62, 0x6e, 0x8f, 0xeb, 0x96, 0xb5, 0xd5, 0x18, 0x72, 0x7b, 0xcc, 0xbf,
	0x04, 0xcc, 0x9f, 0x59, 0x11, 0x3f, 0xf2, 0x6b, 0x75, 0xa2, 0xc6, 0xe2, 0x02, 0x02, 0xab, 0xa5,
	0xc8, 0x44, 0x11, 0x97, 0x81, 0xd5, 0x28, 0x61, 0xa6, 0x3b, 0x61, 0xb7, 0x95, 0x41, 0x26, 0x8a,
	0xa4, 0xfc, 0x8b, 0x58, 0xc0, 0xb9, 0x1e, 0xae, 0xee, 0xb6, 0x32, 0x74, 0xc6, 0x7f, 0x8c, 0x2b,
	0x98, 0x7b, 0x48, 0x46, 0xce, 0xf3, 0x61, 0xbe, 0x82, 0xe4, 0xe9, 0xf3, 0xc3, 0xd6, 0x0f, 0x4a,
	0x31, 0x19, 0x83, 0x97, 0x30, 0x39, 0x75, 0xb9, 0x3f, 0xcc, 0x6f, 0xc8, 0xef, 0x61, 0x31, 0xb4,
	0xc8, 0xe0, 0x15, 0x4c, 0xdd, 0xc8, 0x48, 0x91, 0x85, 0xc5, 0xd9, 0x66, 0xb9, 0xee, 0x2e, 0x39,
	0x94, 0xca, 0x5e, 0xc8, 0x63, 0x98, 0xed, 0xb5, 0x7d, 0xaf, 0x9b, 0x6a, 0xf3, 0x2d, 0x20, 0xda,
	0x6b, 0x45, 0x78, 0x03, 0xd1, 0xa1, 0x6e, 0x2a, 0x1c, 0xaf, 0xa5, 0x63, 0x84, 0xd7, 0x30, 0x39,
	0x10, 0xb1, 0xc1, 0xc4, 0xcd, 0xfa, 0xb6, 0xf4, 0x62, 0x64, 0x92, 0xc1, 0x3b, 0x58, 0xbe, 0x50,
	0xa3, 0xfc, 0xf7, 0x45, 0x67, 0x7a, 0x2c, 0xf5, 0xba, 0xde, 0xa6, 0xee, 0x7f, 0x6e, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x9a, 0x58, 0x10, 0xbb, 0xac, 0x01, 0x00, 0x00,
}
