// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status.proto

/*
Package status is a generated protocol buffer package.

It is generated from these files:
	status.proto

It has these top-level messages:
	StatusRequest
	StatusResponse
*/
package status

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusResponse struct {
	Address      string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Bootstrapped bool   `protobuf:"varint,2,opt,name=bootstrapped" json:"bootstrapped,omitempty"`
	Peers        int64  `protobuf:"varint,3,opt,name=peers" json:"peers,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatusResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StatusResponse) GetBootstrapped() bool {
	if m != nil {
		return m.Bootstrapped
	}
	return false
}

func (m *StatusResponse) GetPeers() int64 {
	if m != nil {
		return m.Peers
	}
	return 0
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "status.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "status.StatusResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Status service

type StatusClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type statusClient struct {
	cc *grpc.ClientConn
}

func NewStatusClient(cc *grpc.ClientConn) StatusClient {
	return &statusClient{cc}
}

func (c *statusClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := grpc.Invoke(ctx, "/status.status/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Status service

type StatusServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
}

func RegisterStatusServer(s *grpc.Server, srv StatusServer) {
	s.RegisterService(&_Status_serviceDesc, srv)
}

func _Status_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatusServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/status.status/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatusServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Status_serviceDesc = grpc.ServiceDesc{
	ServiceName: "status.status",
	HandlerType: (*StatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Status_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "status.proto",
}

func init() { proto.RegisterFile("status.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0xce, 0xc2, 0x30,
	0x0c, 0x46, 0x95, 0xbf, 0xfa, 0x0b, 0x58, 0x05, 0x24, 0x0b, 0x50, 0xc4, 0x14, 0x65, 0xca, 0xd4,
	0x01, 0x06, 0x66, 0xae, 0x10, 0x4e, 0x90, 0x2a, 0x5e, 0x49, 0x88, 0xdd, 0xfb, 0x23, 0x35, 0xed,
	0x50, 0x36, 0xbf, 0xb7, 0xf8, 0x7d, 0xd0, 0xb1, 0x04, 0x19, 0xb9, 0xcf, 0x25, 0x49, 0xc2, 0xb6,
	0x92, 0x3d, 0xc2, 0xfe, 0x35, 0x5d, 0x9e, 0x3e, 0x23, 0xb1, 0xd8, 0x08, 0x87, 0x45, 0x70, 0x4e,
	0x6f, 0x26, 0xd4, 0xb0, 0x09, 0x31, 0x16, 0x62, 0xd6, 0xca, 0x28, 0xb7, 0xf3, 0x0b, 0xa2, 0x85,
	0x6e, 0x48, 0x49, 0x58, 0x4a, 0xc8, 0x99, 0xa2, 0xfe, 0x33, 0xca, 0x6d, 0xfd, 0xca, 0xe1, 0x09,
	0xfe, 0x33, 0x51, 0x61, 0xdd, 0x18, 0xe5, 0x1a, 0x5f, 0xe1, 0xf6, 0x84, 0x39, 0x00, 0x1f, 0xd0,
	0xd6, 0x7f, 0x78, 0xee, 0xe7, 0xc2, 0x55, 0xd0, 0xf5, 0xf2, 0xab, 0x6b, 0xd6, 0xd0, 0x4e, 0x43,
	0xee, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x33, 0x64, 0xf7, 0xd8, 0x00, 0x00, 0x00,
}
