// Code generated by protoc-gen-go. DO NOT EDIT.
// source: smpc.proto

/*
Package smpc is a generated protocol buffer package.

It is generated from these files:
	smpc.proto

It has these top-level messages:
	OpenOrderRequest
	OpenOrderResponse
	CancelOrderRequest
	CancelOrderResponse
	ComputeMessage
	OrderFragment
	DeltaFragment
	Share
*/
package smpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OpenOrderRequest struct {
	Signature     []byte         `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	OrderFragment *OrderFragment `protobuf:"bytes,2,opt,name=orderFragment" json:"orderFragment,omitempty"`
}

func (m *OpenOrderRequest) Reset()                    { *m = OpenOrderRequest{} }
func (m *OpenOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenOrderRequest) ProtoMessage()               {}
func (*OpenOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OpenOrderRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *OpenOrderRequest) GetOrderFragment() *OrderFragment {
	if m != nil {
		return m.OrderFragment
	}
	return nil
}

type OpenOrderResponse struct {
}

func (m *OpenOrderResponse) Reset()                    { *m = OpenOrderResponse{} }
func (m *OpenOrderResponse) String() string            { return proto.CompactTextString(m) }
func (*OpenOrderResponse) ProtoMessage()               {}
func (*OpenOrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CancelOrderRequest struct {
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	OrderId   []byte `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
}

func (m *CancelOrderRequest) Reset()                    { *m = CancelOrderRequest{} }
func (m *CancelOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelOrderRequest) ProtoMessage()               {}
func (*CancelOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CancelOrderRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *CancelOrderRequest) GetOrderId() []byte {
	if m != nil {
		return m.OrderId
	}
	return nil
}

type CancelOrderResponse struct {
}

func (m *CancelOrderResponse) Reset()                    { *m = CancelOrderResponse{} }
func (m *CancelOrderResponse) String() string            { return proto.CompactTextString(m) }
func (*CancelOrderResponse) ProtoMessage()               {}
func (*CancelOrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ComputeMessage struct {
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*ComputeMessage_Address
	//	*ComputeMessage_DeltaFragment
	Value isComputeMessage_Value `protobuf_oneof:"Value"`
}

func (m *ComputeMessage) Reset()                    { *m = ComputeMessage{} }
func (m *ComputeMessage) String() string            { return proto.CompactTextString(m) }
func (*ComputeMessage) ProtoMessage()               {}
func (*ComputeMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type isComputeMessage_Value interface {
	isComputeMessage_Value()
}

type ComputeMessage_Address struct {
	Address string `protobuf:"bytes,2,opt,name=address,oneof"`
}
type ComputeMessage_DeltaFragment struct {
	DeltaFragment *DeltaFragment `protobuf:"bytes,3,opt,name=deltaFragment,oneof"`
}

func (*ComputeMessage_Address) isComputeMessage_Value()       {}
func (*ComputeMessage_DeltaFragment) isComputeMessage_Value() {}

func (m *ComputeMessage) GetValue() isComputeMessage_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ComputeMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ComputeMessage) GetAddress() string {
	if x, ok := m.GetValue().(*ComputeMessage_Address); ok {
		return x.Address
	}
	return ""
}

func (m *ComputeMessage) GetDeltaFragment() *DeltaFragment {
	if x, ok := m.GetValue().(*ComputeMessage_DeltaFragment); ok {
		return x.DeltaFragment
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ComputeMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ComputeMessage_OneofMarshaler, _ComputeMessage_OneofUnmarshaler, _ComputeMessage_OneofSizer, []interface{}{
		(*ComputeMessage_Address)(nil),
		(*ComputeMessage_DeltaFragment)(nil),
	}
}

func _ComputeMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ComputeMessage)
	// Value
	switch x := m.Value.(type) {
	case *ComputeMessage_Address:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Address)
	case *ComputeMessage_DeltaFragment:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DeltaFragment); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ComputeMessage.Value has unexpected type %T", x)
	}
	return nil
}

func _ComputeMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ComputeMessage)
	switch tag {
	case 2: // Value.address
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &ComputeMessage_Address{x}
		return true, err
	case 3: // Value.deltaFragment
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeltaFragment)
		err := b.DecodeMessage(msg)
		m.Value = &ComputeMessage_DeltaFragment{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ComputeMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ComputeMessage)
	// Value
	switch x := m.Value.(type) {
	case *ComputeMessage_Address:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Address)))
		n += len(x.Address)
	case *ComputeMessage_DeltaFragment:
		s := proto.Size(x.DeltaFragment)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OrderFragment struct {
	OrderFragmenId []byte `protobuf:"bytes,1,opt,name=orderFragmenId,proto3" json:"orderFragmenId,omitempty"`
	OrderId        []byte `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Expiry         int64  `protobuf:"varint,3,opt,name=expiry" json:"expiry,omitempty"`
	Type           int32  `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	Tokens         int32  `protobuf:"varint,5,opt,name=tokens" json:"tokens,omitempty"`
	PriceShare     *Share `protobuf:"bytes,6,opt,name=priceShare" json:"priceShare,omitempty"`
	VolumeShare    *Share `protobuf:"bytes,7,opt,name=volumeShare" json:"volumeShare,omitempty"`
}

func (m *OrderFragment) Reset()                    { *m = OrderFragment{} }
func (m *OrderFragment) String() string            { return proto.CompactTextString(m) }
func (*OrderFragment) ProtoMessage()               {}
func (*OrderFragment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OrderFragment) GetOrderFragmenId() []byte {
	if m != nil {
		return m.OrderFragmenId
	}
	return nil
}

func (m *OrderFragment) GetOrderId() []byte {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *OrderFragment) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func (m *OrderFragment) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *OrderFragment) GetTokens() int32 {
	if m != nil {
		return m.Tokens
	}
	return 0
}

func (m *OrderFragment) GetPriceShare() *Share {
	if m != nil {
		return m.PriceShare
	}
	return nil
}

func (m *OrderFragment) GetVolumeShare() *Share {
	if m != nil {
		return m.VolumeShare
	}
	return nil
}

type DeltaFragment struct {
	DeltaFragmentId []byte `protobuf:"bytes,1,opt,name=deltaFragmentId,proto3" json:"deltaFragmentId,omitempty"`
	BuyOrderId      []byte `protobuf:"bytes,2,opt,name=buyOrderId,proto3" json:"buyOrderId,omitempty"`
	SellOrderId     []byte `protobuf:"bytes,3,opt,name=sellOrderId,proto3" json:"sellOrderId,omitempty"`
	PriceShare      *Share `protobuf:"bytes,4,opt,name=priceShare" json:"priceShare,omitempty"`
	VolumeShare     *Share `protobuf:"bytes,5,opt,name=volumeShare" json:"volumeShare,omitempty"`
}

func (m *DeltaFragment) Reset()                    { *m = DeltaFragment{} }
func (m *DeltaFragment) String() string            { return proto.CompactTextString(m) }
func (*DeltaFragment) ProtoMessage()               {}
func (*DeltaFragment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeltaFragment) GetDeltaFragmentId() []byte {
	if m != nil {
		return m.DeltaFragmentId
	}
	return nil
}

func (m *DeltaFragment) GetBuyOrderId() []byte {
	if m != nil {
		return m.BuyOrderId
	}
	return nil
}

func (m *DeltaFragment) GetSellOrderId() []byte {
	if m != nil {
		return m.SellOrderId
	}
	return nil
}

func (m *DeltaFragment) GetPriceShare() *Share {
	if m != nil {
		return m.PriceShare
	}
	return nil
}

func (m *DeltaFragment) GetVolumeShare() *Share {
	if m != nil {
		return m.VolumeShare
	}
	return nil
}

type Share struct {
	Index int64  `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Share) Reset()                    { *m = Share{} }
func (m *Share) String() string            { return proto.CompactTextString(m) }
func (*Share) ProtoMessage()               {}
func (*Share) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Share) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Share) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*OpenOrderRequest)(nil), "smpc.OpenOrderRequest")
	proto.RegisterType((*OpenOrderResponse)(nil), "smpc.OpenOrderResponse")
	proto.RegisterType((*CancelOrderRequest)(nil), "smpc.CancelOrderRequest")
	proto.RegisterType((*CancelOrderResponse)(nil), "smpc.CancelOrderResponse")
	proto.RegisterType((*ComputeMessage)(nil), "smpc.ComputeMessage")
	proto.RegisterType((*OrderFragment)(nil), "smpc.OrderFragment")
	proto.RegisterType((*DeltaFragment)(nil), "smpc.DeltaFragment")
	proto.RegisterType((*Share)(nil), "smpc.Share")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Smpc service

type SmpcClient interface {
	OpenOrder(ctx context.Context, in *OpenOrderRequest, opts ...grpc.CallOption) (*OpenOrderResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	Compute(ctx context.Context, opts ...grpc.CallOption) (Smpc_ComputeClient, error)
}

type smpcClient struct {
	cc *grpc.ClientConn
}

func NewSmpcClient(cc *grpc.ClientConn) SmpcClient {
	return &smpcClient{cc}
}

func (c *smpcClient) OpenOrder(ctx context.Context, in *OpenOrderRequest, opts ...grpc.CallOption) (*OpenOrderResponse, error) {
	out := new(OpenOrderResponse)
	err := grpc.Invoke(ctx, "/smpc.Smpc/OpenOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smpcClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	out := new(CancelOrderResponse)
	err := grpc.Invoke(ctx, "/smpc.Smpc/CancelOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smpcClient) Compute(ctx context.Context, opts ...grpc.CallOption) (Smpc_ComputeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Smpc_serviceDesc.Streams[0], c.cc, "/smpc.Smpc/Compute", opts...)
	if err != nil {
		return nil, err
	}
	x := &smpcComputeClient{stream}
	return x, nil
}

type Smpc_ComputeClient interface {
	Send(*ComputeMessage) error
	Recv() (*ComputeMessage, error)
	grpc.ClientStream
}

type smpcComputeClient struct {
	grpc.ClientStream
}

func (x *smpcComputeClient) Send(m *ComputeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *smpcComputeClient) Recv() (*ComputeMessage, error) {
	m := new(ComputeMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Smpc service

type SmpcServer interface {
	OpenOrder(context.Context, *OpenOrderRequest) (*OpenOrderResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	Compute(Smpc_ComputeServer) error
}

func RegisterSmpcServer(s *grpc.Server, srv SmpcServer) {
	s.RegisterService(&_Smpc_serviceDesc, srv)
}

func _Smpc_OpenOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmpcServer).OpenOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smpc.Smpc/OpenOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmpcServer).OpenOrder(ctx, req.(*OpenOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Smpc_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmpcServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smpc.Smpc/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmpcServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Smpc_Compute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SmpcServer).Compute(&smpcComputeServer{stream})
}

type Smpc_ComputeServer interface {
	Send(*ComputeMessage) error
	Recv() (*ComputeMessage, error)
	grpc.ServerStream
}

type smpcComputeServer struct {
	grpc.ServerStream
}

func (x *smpcComputeServer) Send(m *ComputeMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *smpcComputeServer) Recv() (*ComputeMessage, error) {
	m := new(ComputeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Smpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "smpc.Smpc",
	HandlerType: (*SmpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenOrder",
			Handler:    _Smpc_OpenOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Smpc_CancelOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Compute",
			Handler:       _Smpc_Compute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "smpc.proto",
}

func init() { proto.RegisterFile("smpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6e, 0xd3, 0x40,
	0x10, 0xee, 0x12, 0x3b, 0x56, 0xc6, 0x4d, 0x81, 0x49, 0x29, 0x26, 0x42, 0x28, 0xf2, 0x03, 0xb2,
	0x84, 0xa8, 0x50, 0xfb, 0x54, 0xc1, 0x53, 0x8b, 0x50, 0x2b, 0x81, 0x22, 0x6d, 0x25, 0xde, 0xdd,
	0x78, 0x14, 0xa2, 0xfa, 0x67, 0xd9, 0xb5, 0xab, 0xe6, 0x16, 0xdc, 0x89, 0x43, 0x70, 0x0e, 0x6e,
	0x80, 0xbc, 0xde, 0x84, 0xdd, 0xa4, 0x55, 0xd5, 0xb7, 0x9d, 0x6f, 0x3e, 0xcf, 0xcc, 0x37, 0xde,
	0x6f, 0x01, 0x54, 0x21, 0x66, 0x87, 0x42, 0x56, 0x75, 0x85, 0x5e, 0x7b, 0x8e, 0xaf, 0xe1, 0xd9,
	0x54, 0x50, 0x39, 0x95, 0x19, 0x49, 0x4e, 0x3f, 0x1b, 0x52, 0x35, 0xbe, 0x86, 0x81, 0x5a, 0xcc,
	0xcb, 0xb4, 0x6e, 0x24, 0x45, 0x6c, 0xc2, 0x92, 0x5d, 0xfe, 0x1f, 0xc0, 0x13, 0x18, 0x56, 0x2d,
	0xfb, 0x8b, 0x4c, 0xe7, 0x05, 0x95, 0x75, 0xf4, 0x64, 0xc2, 0x92, 0xf0, 0x68, 0x74, 0xa8, 0x6b,
	0x4f, 0xed, 0x14, 0x77, 0x99, 0xf1, 0x08, 0x9e, 0x5b, 0xcd, 0x94, 0xa8, 0x4a, 0x45, 0xf1, 0x57,
	0xc0, 0xb3, 0xb4, 0x9c, 0x51, 0xfe, 0x88, 0x19, 0x22, 0x08, 0x74, 0xe5, 0x8b, 0x4c, 0x77, 0xdf,
	0xe5, 0xab, 0x30, 0x7e, 0x01, 0x23, 0xa7, 0x9a, 0x69, 0xf2, 0x8b, 0xc1, 0xde, 0x59, 0x55, 0x88,
	0xa6, 0xa6, 0x6f, 0xa4, 0x54, 0x3a, 0xa7, 0x07, 0x3a, 0x8c, 0x21, 0x48, 0xb3, 0x4c, 0x92, 0x52,
	0xba, 0xc3, 0xe0, 0x7c, 0x87, 0xaf, 0x00, 0xfc, 0x08, 0xc3, 0x8c, 0xf2, 0x3a, 0x5d, 0x6f, 0xa0,
	0x67, 0x6f, 0xe0, 0xb3, 0x9d, 0x3a, 0xdf, 0xe1, 0x2e, 0xf7, 0x34, 0x00, 0xff, 0x7b, 0x9a, 0x37,
	0x14, 0xff, 0x65, 0x30, 0x74, 0xb6, 0x85, 0x6f, 0x61, 0xcf, 0xde, 0xd7, 0x45, 0x66, 0xc6, 0xda,
	0x40, 0xef, 0x57, 0x8f, 0x07, 0xd0, 0xa7, 0x5b, 0xb1, 0x90, 0x4b, 0x3d, 0x52, 0x8f, 0x9b, 0x08,
	0x11, 0xbc, 0x7a, 0x29, 0x28, 0xf2, 0x26, 0x2c, 0xf1, 0xb9, 0x3e, 0xb7, 0xdc, 0xba, 0xba, 0xa6,
	0x52, 0x45, 0xbe, 0x46, 0x4d, 0x84, 0xef, 0x00, 0x84, 0x5c, 0xcc, 0xe8, 0xf2, 0x47, 0x2a, 0x29,
	0xea, 0x6b, 0x69, 0x61, 0x27, 0x4d, 0x43, 0xdc, 0x4a, 0xe3, 0x7b, 0x08, 0x6f, 0xaa, 0xbc, 0x29,
	0x0c, 0x3b, 0xd8, 0x66, 0xdb, 0xf9, 0xf8, 0x0f, 0x83, 0xa1, 0xb3, 0x1f, 0x4c, 0xe0, 0xa9, 0xb3,
	0x9f, 0xb5, 0xe8, 0x4d, 0x18, 0xdf, 0x00, 0x5c, 0x35, 0xcb, 0xa9, 0x23, 0xdc, 0x42, 0x70, 0x02,
	0xa1, 0xa2, 0x3c, 0x5f, 0x11, 0x7a, 0x9a, 0x60, 0x43, 0x1b, 0xca, 0xbc, 0x47, 0x29, 0xf3, 0x1f,
	0x50, 0x76, 0x0c, 0x7e, 0xf7, 0xdd, 0x3e, 0xf8, 0x8b, 0x32, 0xa3, 0x5b, 0x2d, 0xa3, 0xc7, 0xbb,
	0xa0, 0x45, 0x6f, 0xda, 0xbf, 0x6e, 0xe6, 0xee, 0x82, 0xa3, 0xdf, 0x0c, 0xbc, 0xcb, 0x42, 0xcc,
	0xf0, 0x13, 0x0c, 0xd6, 0xc6, 0xc0, 0x03, 0xe3, 0xa4, 0x0d, 0x5b, 0x8e, 0x5f, 0x6e, 0xe1, 0xdd,
	0xe5, 0xc6, 0x53, 0x08, 0xad, 0x3b, 0x8f, 0x51, 0xc7, 0xdb, 0x36, 0xd5, 0xf8, 0xd5, 0x1d, 0x19,
	0x53, 0xe3, 0x04, 0x02, 0xe3, 0x0f, 0xdc, 0x37, 0x2c, 0xc7, 0x2e, 0xe3, 0x3b, 0xd1, 0x84, 0x7d,
	0x60, 0x57, 0x7d, 0xfd, 0x9e, 0x1c, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xfb, 0xff, 0xc8,
	0x5d, 0x04, 0x00, 0x00,
}
